# Generated by Django 5.1.3 on 2024-12-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='skills',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='summary',
        ),
    ]
