# Generated by Django 5.1.3 on 2024-12-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_education_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
