# Generated by Django 5.1.3 on 2024-12-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_workexperience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(choices=[('fluent', 'Fluent'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('fluent', 'Fluent'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
    ]
